services:
  mongo:
    container_name: database_container
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: greenhouse_db

  mongo-express:
    container_name: mongo_dashboard_container
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  
  api:
    container_name: greenhouse_api_container
    build: .
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongodb: {}